batch_size: 8
iters: 40000 #100000->20000

train_dataset:
  type: Dataset
  dataset_root: /home/aistudio
  train_path: /home/aistudio/train.txt
  num_classes: 2
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 1.5
      scale_step_size: 0.25
    - type: RandomHorizontalFlip
    #3th add
    - type: RandomVerticalFlip 
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Resize
      target_size: [384, 384]
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: train

val_dataset:
  type: Dataset
  dataset_root: /home/aistudio
  val_path: /home/aistudio/val.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [384, 384]
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: val


model:
  type: DeepLabV3
  num_classes: 2
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: output_deeplabv3_10/iter_100000/model.pdparams

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 1.0e-3 #1.0-4

lr_scheduler:
  #type: PolynomialDecay
  type: CosineWarmup
  #0.01->0.0001
  learning_rate: 0.001 
  start_lr: 0.
  eta_min: 0.
  #end_lr: 0
  #power: 0.9
    



loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        #- type: LovaszSoftmaxLoss
        #- type: DiceLoss
      coef: [1.0]
  coef: [1]